export const payload: object = 
  {
    pagos: {
      listado: {
        ord: "fecha",
        busqueda: "",
        dord: "desc",
        emisor: "11",
        cuenta_bancaria: "",
        movimiento_pago: "0",
        id: "",
        fecha: "",
        num_operacion: "",
        comprobante_pagado: "",
        empresa_nombre: "",
        receptor_nombre: "",
        monto_recibido: "",
        moneda: "null",
        cuenta_bancaria_movimiento: "",
        status_pago: "null",
        columnas: [
          "fecha",
          "forma",
          "forma_pago_nombre",
          "num_operacion",
          "comprobante_pagado",
          "empresa",
          "empresa_nombre",
          "receptor",
          "receptor_nombre",
          "monto",
          "monto_recibido",
          "cuenta_bancaria_movimiento",
          "cuenta_bancaria_movimiento_nombre",
          "status_pago",
          "status_pago_nombre",
        ],
      },
    },
  };
